-- =====================================================
-- Migration 012: Importar dados completos de Jornadas
-- Projeto 5 (GTM Clone) - Entidade ID 18
-- Tabela: projeto_dados (coluna dados como JSON)
-- =====================================================

-- Limpar dados existentes de jornadas do projeto 5
DELETE FROM projeto_dados WHERE entidade_id = 18 AND projeto_id = 5;

-- Jornada 1: Cadastro de Cliente
INSERT INTO projeto_dados (projeto_id, entidade_id, dados)
VALUES (5, 18, '{"nome":"Cadastro de Cliente","icone":"👤","ordem":1,"status":"Em Andamento","as_is":"Processo manual e fragmentado onde o vendedor coleta dados do cliente via formulários em papel ou planilhas Excel, envia para o SmartCenter por e-mail, que então digita manualmente no SAP.","passos_as_is":"Vendedor visita cliente|Coleta dados em formulário físico|Envia para SmartCenter via e-mail|SmartCenter analisa e digita no SAP|Verificação manual de duplicados|Cadastro finalizado após correções","problemas_as_is":"Tempo excessivo (2-3 dias)|Erros de digitação|Cadastros duplicados|Sem validação automática|Dependência do SmartCenter|Dados inconsistentes","tempo_medio_as_is":"2 a 3 dias úteis","to_be":"Cadastro automatizado via integração SINTEGRA no Salesforce. Vendedor digita CNPJ, clica Integrar SINTEGRA e sistema preenche dados automaticamente.","passos_to_be":"Acessa Salesforce|Cria Conta e seleciona tipo|Preenche CNPJ|Clica Integrar SINTEGRA|Sistema preenche dados|Valida duplicidade|Envia SAP para sincronização","beneficios_to_be":"Cadastro em 5 minutos|Sem erros manuais|Validação SINTEGRA|Deduplicação automática|CNAE correto|Rastreabilidade completa","tempo_medio_to_be":"5 minutos","areas_impactadas":"Comercial|SmartCenter|TI|Atendimento|Financeiro|Logística","sistemas_tecnicos":"Salesforce|SAP ECC|SINTEGRA|Middleware","fonte_reuniao":"10/12/2025","fontes_reuniao":"10/12/2025 - Cadastro de Cliente|16/12/2025 - Revisão de Cadastro","pendencias":"Integração Portal Logístico|Padronização de celulares|Definição de regras para concorrentes|Critérios de Canal por CNAE","prerequisitos":"API SINTEGRA configurada|Middleware SAP configurado|Perfis de usuário configurados|Usuários treinados","tipos_conta":[{"tipo":"Pessoa Jurídica (PJ)","descrição":"Empresas com CNPJ","recordType":"PJ_Standard"},{"tipo":"Pessoa Física (PF)","descrição":"Clientes com CPF","recordType":"PF_Standard"},{"tipo":"Parceiro Agrupador","descrição":"Holdings","recordType":"Agrupador"}],"campos_processo":[{"campo":"CNPJ","preenchimento":"Manual","validação":"SINTEGRA"},{"campo":"Razão Social","preenchimento":"Automático (SINTEGRA)"},{"campo":"CNAE","preenchimento":"Automático (SINTEGRA)"},{"campo":"Termo de Pesquisa","preenchimento":"Manual","validação":"Duplicidade"}],"regras_negocio":[{"regra":"Validação de Duplicidade","descrição":"Verifica Termo de Pesquisa existente"},{"regra":"Preenchimento SINTEGRA","descrição":"Preenche IE, CNAE, Endereço automaticamente"},{"regra":"Sincronização SAP","descrição":"Botão Enviar SAP sincroniza dados"}],"integracoes":[{"origem":"Salesforce","destino":"SINTEGRA","tipo":"API"},{"origem":"Salesforce","destino":"SAP","tipo":"Middleware"}],"ciclos_teste":[{"documento":"876268","título":"CNAE","ciclo":"P1"},{"documento":"899139","título":"Termo de Pesquisa","ciclo":"P2"}],"detalhes":{"sintegra":"Integração automática CNPJ","deduplicação":"Validação por Termo de Pesquisa","integração":"Salesforce → SAP via middleware"}}');

-- Jornada 2: Áreas de Vendas
INSERT INTO projeto_dados (projeto_id, entidade_id, dados)
VALUES (5, 18, '{"nome":"Áreas de Vendas","icone":"🏢","ordem":2,"status":"Em Andamento","as_is":"Atribuição manual de canais e escritórios","passos_as_is":"Identificar tipo de cliente|Definir canal manualmente|Atribuir escritório|Configurar no SAP","problemas_as_is":"Erros de classificação|Canais incorretos|Retrabalho frequente","tempo_medio_as_is":"1 dia","to_be":"Canais 20, 30, 40, 25 automatizados","passos_to_be":"Sistema identifica tipo de cliente|Canal sugerido automaticamente|Usuário confirma|Integração automática","beneficios_to_be":"Classificação correta|Redução de erros|Processo padronizado","tempo_medio_to_be":"Imediato","areas_impactadas":"Comercial|Operações","fonte_reuniao":"10/12/2025","regras_negocio":["Canal definido pelo CNAE","Cluster calculado por algoritmo","Exceções via workflow de 2 níveis"],"detalhes":{"canais":{"20":"Indústria","25":"Casos Especiais","30":"Distribuição","40":"Consumo/Varejo"},"clusters":{"Corporativas":"Grandes contas","Especiais":"Tratamento diferenciado","Regionais":"Atuação regional","Dispersas":"Contas menores"}}}');

-- Jornada 3: Documentos Fiscais
INSERT INTO projeto_dados (projeto_id, entidade_id, dados)
VALUES (5, 18, '{"nome":"Documentos Fiscais","icone":"📄","ordem":3,"status":"Em Andamento","as_is":"Emissão manual de XML e DANFE","passos_as_is":"Faturamento no SAP|Gera XML manualmente|Gera DANFE manualmente|Envia por email","problemas_as_is":"Processo lento|Erros de digitação|Atrasos no envio|Dependência de pessoa","tempo_medio_as_is":"30 minutos por nota","to_be":"Emissão automática integrada","passos_to_be":"SAP dispara trigger|XML gerado automaticamente|DANFE gerado automaticamente|Envio automático email/portal","beneficios_to_be":"Processo instantâneo|Sem erros manuais|Cliente recebe imediatamente|Rastreabilidade completa","tempo_medio_to_be":"Automático","areas_impactadas":"Fiscal|TI|Comercial","sistemas_tecnicos":"SAP|Araujo|Salesforce|Portal Cliente","fonte_reuniao":"16/12/2025","detalhes":{"trigger":"SAP dispara processo no Araujo","documentos":["XML da NF-e","DANFE","Certificado de Qualidade"],"envio":"Email automático + portal"}}');

-- Jornada 4: Gestão de Contatos
INSERT INTO projeto_dados (projeto_id, entidade_id, dados)
VALUES (5, 18, '{"nome":"Gestão de Contatos","icone":"📞","ordem":4,"status":"Pendente","as_is":"Cadastro manual de contatos","passos_as_is":"Vendedor coleta dados|Digita manualmente no sistema|Sem validação de duplicados","problemas_as_is":"Dados incompletos|Contatos duplicados|Informações desatualizadas","tempo_medio_as_is":"15 minutos","to_be":"Auto-preenchimento e validação","passos_to_be":"Sistema sugere contatos|Validação de email/telefone|Deduplicação automática|Histórico de interações","beneficios_to_be":"Dados completos|Sem duplicações|Contatos atualizados","tempo_medio_to_be":"2 minutos","areas_impactadas":"Comercial|Marketing","fonte_reuniao":"16/12/2025","detalhes":{"criticidade":"PRE-REQUISITO para Autoatendimento","validações":["Formato de email","Formato de telefone","CPF/CNPJ"],"deduplicação":"Matching por email, telefone e nome"},"prerequisitos":"autoatendimento"}');

-- Jornada 5: Portal Logístico
INSERT INTO projeto_dados (projeto_id, entidade_id, dados)
VALUES (5, 18, '{"nome":"Portal Logístico","icone":"🚚","ordem":5,"status":"Pendente","as_is":"Portal separado do SAP","passos_as_is":"Dados digitados no portal|Replicação manual para SAP|Conferência manual","problemas_as_is":"Redundância de dados|Inconsistências entre sistemas|Retrabalho","tempo_medio_as_is":"Variável","to_be":"Integração Portal-SAP","passos_to_be":"Dados inseridos uma vez|Sincronização automática|Visão única integrada","beneficios_to_be":"Eliminação de redundância|Dados consistentes|Processo otimizado","tempo_medio_to_be":"Automático","areas_impactadas":"Logística|TI","fonte_reuniao":"16/12/2025"}');

-- Jornada 6: Financeiro/Crédito
INSERT INTO projeto_dados (projeto_id, entidade_id, dados)
VALUES (5, 18, '{"nome":"Financeiro/Crédito","icone":"💰","ordem":6,"status":"Em Andamento","as_is":"Ficha de crédito manual","passos_as_is":"Análise manual de crédito|Ficha física/Excel|Aprovação por email","problemas_as_is":"Processo lento|Sem visibilidade|Risco de erros","tempo_medio_as_is":"2-3 dias","to_be":"FSCM integrado","passos_to_be":"Análise automática via FSCM|Limite calculado pelo sistema|Aprovação digital com workflow","beneficios_to_be":"Análise em tempo real|Visibilidade total|Processo auditável","tempo_medio_to_be":"Horas","areas_impactadas":"Financeiro|Comercial","sistemas_tecnicos":"Salesforce|SAP FSCM|ASCP|Bureaus de Crédito","fonte_reuniao":"04/12/2025","detalhes":{"áreasCrédito":{"BBA":"Limite Interno Belgo","CSP":"Supply/Belgo Cash","DBA":"Distribuição","ALPE":"Aços Longos PE"},"fscm":"Financial Supply Chain Management","workflow":"Analista -> Gestor -> Diretoria"}}');

-- Jornada 7: Rastreamento de Concorrentes
INSERT INTO projeto_dados (projeto_id, entidade_id, dados)
VALUES (5, 18, '{"nome":"Rastreamento de Concorrentes","icone":"🎯","ordem":7,"status":"Pendente","as_is":"Registro manual e esporádico","passos_as_is":"Vendedor anota informações|Planilhas individuais|Sem consolidação","problemas_as_is":"Dados fragmentados|Informações desatualizadas|Sem análise","tempo_medio_as_is":"N/A","to_be":"Gestão sistemática no CRM","passos_to_be":"Registro estruturado no Salesforce|Vinculação com oportunidades|Relatórios automáticos","beneficios_to_be":"Visão consolidada|Análise de mercado|Decisões baseadas em dados","tempo_medio_to_be":"5 minutos","areas_impactadas":"Comercial|Marketing|Estratégia","fonte_reuniao":"10/12/2025"}');

-- Jornada 8: Autoatendimento
INSERT INTO projeto_dados (projeto_id, entidade_id, dados)
VALUES (5, 18, '{"nome":"Autoatendimento","icone":"🖥️","ordem":8,"status":"Em Desenvolvimento","as_is":"Inexistente - Cliente depende totalmente do vendedor ou Smart Center","passos_as_is":"Cliente liga para vendedor|Vendedor consulta sistemas manualmente|Retorna informação por telefone/email|Cliente aguarda sem previsão","problemas_as_is":"Dependência total do vendedor|Demora no atendimento|Sem autonomia do cliente|Smart Center sobrecarregado","tempo_medio_as_is":"Horas/Dias","to_be":"Portal self-service e Bot Einstein via WhatsApp para atendimento 24/7","passos_to_be":"Cliente acessa portal ou WhatsApp|Bot Einstein faz autenticação|Consulta status de pedidos|Download de documentos fiscais|Rastreamento de entregas|2ª via de boletos|Transbordo para Smart Center se necessário","beneficios_to_be":"Autonomia total do cliente|Atendimento 24/7|Redução de chamados|Consultas instantâneas|Integração Service Cloud","tempo_medio_to_be":"Imediato","areas_impactadas":"Comercial|Atendimento|TI|Smart Center","fonte_reuniao":"16/12/2025","fontes_reuniao":"16/12/2025 - Documentos Fiscais e Autoatendimento|07/01/2026 - Bot Einstein Planejamento","detalhes":{"prerequisito":"Depende de dados de contato corretos","funcionalidades":["Status pedidos","Download XML/DANFE","Rastreamento","2ª via boleto","Certificados","Bot WhatsApp"],"botEinstein":{"canais":["WhatsApp","Portal Web"],"orcamento2026":"400.000 BRL","status":"MVP em desenvolvimento"}},"prerequisitos":"contatos"}');

-- Jornada 9: Workflow Pricing
INSERT INTO projeto_dados (projeto_id, entidade_id, dados)
VALUES (5, 18, '{"nome":"Workflow Pricing","icone":"💲","ordem":9,"status":"Em Andamento","as_is":"Descontos sem controle centralizado","passos_as_is":"Vendedor negocia desconto|Aprovação informal|Desconto manual no pedido|Sem registro","problemas_as_is":"Sem controle|Aprovações informais|Sem vigência|Margens corroídas","tempo_medio_as_is":"Variável","to_be":"Workflow de aprovação com condition YDCF no SAP","passos_to_be":"Acessa Pricing no Salesforce|Navega hierarquia de materiais (6 níveis)|Define % desconto e vigência|Nível 1: Time Pricing aprova|Nível 2: Gerente aprova|YDCF criada no SAP","beneficios_to_be":"Controle total|Rastreabilidade|Workflow 2 níveis|Vigência automática|Integração SAP","tempo_medio_to_be":"1-2 dias","areas_impactadas":"Comercial|Marketing|Pricing|TI","sistemas_tecnicos":"Salesforce|SAP","fonte_reuniao":"16/12/2025","detalhes":{"hierarquiaMateriais":["Unidades","Macro Segmentos","Macro Detalhado","Segmento","Grupo Mercadoria","Material"],"conditionSAP":"YDCF - Desconto de Cliente","fluxoAprovação":[{"nível":1,"aprovador":"Time Pricing"},{"nível":2,"aprovador":"Gerente Escritório"}]}}');

-- Jornada 10: Cotação e Ordem de Vendas
INSERT INTO projeto_dados (projeto_id, entidade_id, dados)
VALUES (5, 18, '{"nome":"Cotação e Ordem de Vendas","icone":"📋","ordem":10,"status":"Em Andamento","as_is":"Processo manual de cotação","passos_as_is":"Consulta preço no SAP|Verifica estoque manualmente|Monta cotação em Excel|Digita pedido no SAP","problemas_as_is":"Processo lento|Preços desatualizados|Sem ATP|Retrabalho","tempo_medio_as_is":"Horas","to_be":"Cotação integrada com ATP e conversão automática","passos_to_be":"Cria cotação no Salesforce|Sistema busca preços do SAP|ATP verifica disponibilidade|Descontos YDCF automáticos|Conversão para OV","beneficios_to_be":"Processo ágil|Preços atualizados|ATP em tempo real|Visibilidade completa","tempo_medio_to_be":"Minutos","areas_impactadas":"Comercial|Logística|Financeiro","sistemas_tecnicos":"Salesforce|SAP","fonte_reuniao":"10/12/2025","detalhes":{"atp":"Available to Promise - disponibilidade em tempo real","farol":"Status OV (verde/amarelo/vermelho)"}}');

-- Jornada 11: Hub de Gestão OC
INSERT INTO projeto_dados (projeto_id, entidade_id, dados)
VALUES (5, 18, '{"nome":"Hub de Gestão OC","icone":"⚙️","ordem":11,"status":"Em Andamento","as_is":"Gestão descentralizada de grupos","passos_as_is":"Solicitações por email|TI configura manualmente|Sem visibilidade de grupos|Logs separados","problemas_as_is":"Processo manual|Sem self-service|Difícil auditar|Logs dispersos","tempo_medio_as_is":"Dias","to_be":"Hub centralizado com gestão via LWC","passos_to_be":"Gestor acessa Gerenciar Grupos|Visualiza grupos|Adiciona/remove membros|Busca por email/nome|Visualiza logs","beneficios_to_be":"Self-service|Visibilidade de membros|Controle de perfis|Logs centralizados","tempo_medio_to_be":"Minutos","areas_impactadas":"TI|Todas as áreas","sistemas_tecnicos":"Salesforce (LWC)","fonte_reuniao":"Documentos de teste","detalhes":{"lwc":"Lightning Web Component","grupos":["Comercial","Qualidade","Sistemas"]}}');

-- Jornada 12: Restrições Logísticas
INSERT INTO projeto_dados (projeto_id, entidade_id, dados)
VALUES (5, 18, '{"nome":"Restrições Logísticas","icone":"🚛","ordem":12,"status":"Pendente","as_is":"Restrições de entrega gerenciadas em sistemas separados sem integração","passos_as_is":"Informações no Portal Logístico|Dados duplicados no SAP|Vendedor consulta XD03|Sem visibilidade cliente|Agendamentos por telefone","problemas_as_is":"Redundância de dados|Inconsistências|Cliente sem visibilidade|Agendamentos manuais|Sem integração","tempo_medio_as_is":"Variável","to_be":"Integração Salesforce → SAP → Portal Logístico em tempo real","passos_to_be":"Vendedor registra restrições no Salesforce|Sincroniza automaticamente com SAP|Integração com Portal Logístico|Cliente visualiza no autoatendimento|Agendamentos online","beneficios_to_be":"Dados unificados|Visibilidade em tempo real|Cliente com autonomia|Eliminação de redundância|Processo otimizado","tempo_medio_to_be":"Imediato","areas_impactadas":"Logística|Comercial|TI|Atendimento","sistemas_tecnicos":"Salesforce|SAP ECC|Portal Logístico","fonte_reuniao":"10/12/2025","detalhes":{"tiposRestrição":[{"tipo":"Veículo","descrição":"Restrições de tipo de veículo"},{"tipo":"Janela de Entrega","descrição":"Horários permitidos"},{"tipo":"Agendamento","descrição":"Necessidade de agendamento prévio"},{"tipo":"Descarga","descrição":"Condições especiais de descarga"}],"transaçãoSAP":"XD03 - Exibir Cliente","integração":"Portal ↔ SAP ↔ Salesforce"},"pendencias":"Integração Portal-SAP pendente|Definição de campos obrigatórios|Reunião com equipe logística"}');

-- Jornada 13: Market Share e Concorrentes
INSERT INTO projeto_dados (projeto_id, entidade_id, dados)
VALUES (5, 18, '{"nome":"Market Share e Concorrentes","icone":"📊","ordem":13,"status":"Pendente","as_is":"Informações de concorrentes e market share dispersas, sem gestão centralizada","passos_as_is":"Vendedor coleta informações informalmente|Dados em planilhas individuais|Projetos perdidos não vinculados|Sem histórico de market share|Análise manual","problemas_as_is":"Concorrentes sazonais e dinâmicos|Difícil vincular projetos perdidos|Sem visão de share of wallet|Dados fragmentados|Impossível rastrear tendências","tempo_medio_as_is":"N/A","to_be":"Gestão centralizada de concorrentes e market share no Salesforce com análise automatizada","passos_to_be":"Cadastro normalizado de concorrentes|Registro de share of wallet por cliente|Vinculação de oportunidades perdidas|Dashboard de análise automático|Histórico de evolução de market share","beneficios_to_be":"Visão consolidada de concorrentes|Análise de share of wallet|Identificação de tendências|Decisões baseadas em dados|Rastreamento de projetos perdidos","tempo_medio_to_be":"5 minutos por registro","areas_impactadas":"Comercial|Marketing|Estratégia|Inteligência de Mercado","sistemas_tecnicos":"Salesforce|Power BI","fonte_reuniao":"10/12/2025","detalhes":{"shareOfWallet":{"descrição":"Percentual de compra do cliente na Belgo vs concorrentes","cálculo":"Volume Belgo / Volume Total Cliente","objetivo":"Identificar potencial de crescimento"},"concorrentes":{"cadastro":"Lista normalizada pela TI","desafio":"Concorrentes sazonais e dinâmicos"},"marketShareTipos":{"estratégico":"Visão de longo prazo por segmento","tático":"Visão de curto prazo por oportunidade"}},"pendencias":"Normalização de cadastro pela TI|Critérios para projetos perdidos|Discussão com Edmundo"}');

-- Jornada 14: AMD Cross Company
INSERT INTO projeto_dados (projeto_id, entidade_id, dados)
VALUES (5, 18, '{"nome":"AMD Cross Company","icone":"🔄","ordem":14,"status":"Pendente","as_is":"Processo de vendas entre empresas do grupo ArcelorMittal não contemplado no Salesforce","passos_as_is":"AMD gerencia vendas em sistema próprio|Transações cross company manuais|Sem integração com Salesforce|Visibilidade limitada","problemas_as_is":"AMD sem funcionalidades no Salesforce|Cross Company não contemplado|Falta rastreabilidade intercompany|Difícil consolidar resultados","tempo_medio_as_is":"Variável","to_be":"Integração do processo AMD Cross Company no Salesforce para gestão unificada de vendas intercompany","passos_to_be":"Registro de transações AMD no Salesforce|Workflow de aprovação cross company|Integração com SAP para contabilização|Relatórios consolidados|Visibilidade completa","beneficios_to_be":"Gestão unificada de vendas do grupo|Rastreabilidade intercompany|Consolidação de resultados|Visibilidade para todas as áreas|Processo padronizado","tempo_medio_to_be":"A definir","areas_impactadas":"Comercial|Financeiro|Controladoria|AMD","sistemas_tecnicos":"Salesforce|SAP ECC|Sistema AMD","fonte_reuniao":"10/12/2025","detalhes":{"amd":{"nome":"ArcelorMittal Distribuição","descrição":"Empresa do grupo para distribuição","processo":"Vendas intercompany"},"crossCompany":{"descrição":"Transações entre empresas do grupo","desafio":"Contabilização entre entidades legais"},"responsável":"Renata Mello e Victoria"},"pendencias":"Reunião com Renata e Victoria|Escopo AMD no Salesforce|Mapeamento cross company"}');
