-- =====================================================
-- Migration 013: Importar dados completos de Reunioes
-- Projeto 5 (GTM Clone) - Entidade ID 20
-- =====================================================

-- Limpar dados existentes de reunioes do projeto 5
DELETE FROM projeto_dados WHERE entidade_id = 20 AND projeto_id = 5;

-- Reuniao R1: Kickoff e Alinhamento
INSERT INTO projeto_dados (projeto_id, entidade_id, dados)
VALUES (5, 20, '{"id":"R1","data":"2025-12-04","titulo":"Kickoff e Alinhamento de Key Users","duracao":"2h","tipo":"workshop","resumo":"Reunião inaugural dos workshops AS-IS/TO-BE. Apresentada visão geral do projeto GTM/CRM para os key users. Comunicada transição de liderança com saída de Dani Tamerão e licença maternidade de Audrey. Estabelecido compromisso de 2 horas semanais por key user para testes.","participantes":"Leandro Cruz|Thalita Rhein|Leandro Gimenez|Vanessa Souza|Bruno Machado|Marcio Silva","topicos":"Visão geral projeto GTM/CRM|Transição de liderança|Papel e responsabilidades dos key users|Cronograma de workshops","decisoes":"Todos gerentes devem identificar formalmente seus key users|Key users devem dedicar 2h semanais ao projeto","problemas":"Key users não sabiam que eram key users|Usuários perguntando: O que preciso testar?","acoes":"","jornadas_relacionadas":"cadastro-cliente|areas-vendas"}');

-- Reuniao R2: Cadastro Cliente, Áreas de Vendas
INSERT INTO projeto_dados (projeto_id, entidade_id, dados)
VALUES (5, 20, '{"id":"R2","data":"2025-12-10","titulo":"Cadastro Cliente, Áreas de Vendas e Concorrentes","duracao":"2h","tipo":"workshop","resumo":"Workshop detalhado sobre processos de cadastro de cliente utilizando SINTEGRA para consulta de dados. Explicados os tipos de conta (PJ, PF, Parceiro Agrupador). Mapeadas as áreas de vendas e canais de distribuição. Francine Gayer levantou questão sobre sazonalidade dos dados de concorrentes.","participantes":"Leandro Cruz|Thalita Rhein|Leandro Gimenez|Joao Endo|Francine Gayer|Bruno Machado|Daniel Goncalves|Jessica Vaz|Renata Mello","topicos":"Cadastro de cliente via SINTEGRA|Tipos de conta (PJ/PF/Agrupador)|Áreas de vendas e canais|Documentos fiscais|Contatos|Concorrentes|ASCP (Crédito)","decisoes":"Normalização de concorrentes será feita pela TI|Reunião específica com Edmundo sobre gestão de concorrentes","problemas":"Dados de concorrentes são sazonais e dinâmicos|AMD não tem funcionalidades no Salesforce","acoes":"","jornadas_relacionadas":"cadastro-cliente|areas-vendas|documentos-fiscais|contatos|concorrentes|financeiro"}');

-- Reuniao R3: Regras de Clusterização
INSERT INTO projeto_dados (projeto_id, entidade_id, dados)
VALUES (5, 20, '{"id":"R3","data":"2025-12-12","titulo":"Regras de Clusterização e Apuração de Resultados","duracao":"53 min","tipo":"workshop","resumo":"Definição completa do modelo de clusterização de clientes. Estabelecidas 3 dimensões: setor do cliente, atratividade e região geográfica. Definidos 4 clusters: Contas Corporativas, Especiais, Regionais e Dispersas. Discutida implementação do cálculo automático no CRM Salesforce.","participantes":"Maria Ciorlia|Leandro Cruz|Frederico Kinoshita|Fernanda Monteiro|Thalita Rhein|Jefferson Pinheiro|Marcelo Almeida|Luis Riqueti","topicos":"Visão geral de clusterização|3 dimensões de clusterização|4 clusters de clientes|Cálculo automático no CRM|Custo de servir por cluster|Integração com relatórios","decisoes":"Algoritmo de cluster será automático no CRM|Higiene de dados de clientes necessária|Reuniões de acompanhamento com DCPC e DCCI","problemas":"Atribuições manuais de cluster incorretas|Necessidade de fonte de dados unificada para relatórios","acoes":"","jornadas_relacionadas":"cadastro-cliente|hub-gestao|workflow-pricing"}');

-- Reuniao R4: Documentos Fiscais e Portal de Autoatendimento
INSERT INTO projeto_dados (projeto_id, entidade_id, dados)
VALUES (5, 20, '{"id":"R4","data":"2025-12-16","titulo":"Documentos Fiscais e Portal de Autoatendimento","duracao":"2h","tipo":"workshop","resumo":"Cobertura dos processos de documentos fiscais incluindo NF-e, XML, DANFE e boletos. Apresentadas integrações com sistemas Daniel e Spa. Destacada criticidade de manter dados de contato atualizados para funcionamento do autoatendimento. Identificada pendência crítica na integração do Portal Logístico com SAP.","participantes":"Leandro Cruz|Thalita Rhein|Joao Endo|Francine Gayer|Vanessa Souza|Bruno Machado|Frank Silva","topicos":"Download documentos fiscais|Integração Daniel/Spa|Dados de contato|Portal Autoatendimento|App Mobile","decisoes":"Campanha de atualização de cadastros iniciada|Follow-up sobre integração Portal Logístico-SAP","problemas":"Portal Logístico não integrado com SAP|Dados de contato incompletos","acoes":"","jornadas_relacionadas":"documentos-fiscais|autoatendimento|contatos|logistica"}');

-- Reuniao R5: Relatórios GTM e Segment Report
INSERT INTO projeto_dados (projeto_id, entidade_id, dados)
VALUES (5, 20, '{"id":"R5","data":"2025-12-17","titulo":"Relatórios GTM e Segment Report","duracao":"1h","tipo":"workshop","resumo":"Discussão focada em segmentação de dados de clientes para relatórios analíticos. Apresentada estrutura de hierarquia de dados para garantir consistência. Definidas responsabilidades de governança e ownership para manutenção das hierarquias.","participantes":"Luis Riqueti|Fabricio França|Thalita Rhein|Fernanda Monteiro","topicos":"Segmentação de dados|Programa de fidelidade|Hierarquia de relatórios|Governança e ownership|Integração Salesforce","decisoes":"Validar campo agregador de parceiros|Definir descrição do campo cluster|Estabelecer governança para hierarquias","problemas":"Necessidade de consistência entre CPV e segmentação","acoes":"","jornadas_relacionadas":"hub-gestao|workflow-pricing|cadastro-cliente"}');

-- Reuniao R6: URGENTE - Revisão GTM e Nova Estrutura Comercial
INSERT INTO projeto_dados (projeto_id, entidade_id, dados)
VALUES (5, 20, '{"id":"R6","data":"2025-12-22","titulo":"URGENTE - Revisão GTM e Nova Estrutura Comercial","duracao":"2h30","tipo":"estrategico","resumo":"Reunião estratégica urgente sobre reestruturação comercial. Nova estrutura com diretoria comercial e 4 macro setores: Alta Energia, Agricultura, Indústria e Construção Civil. Todos os 46 segmentos serão realocados. Definidas mudanças na gestão regional.","participantes":"Leandro Gimenez|Leandro Cruz|Thalita Rhein|Maria Ciorlia|Luis Riqueti|Jefferson Pinheiro|Fabricio França","topicos":"Nova estrutura organizacional|4 macro setores comerciais|Gestão regional|Key accounts|Workflow de aprovação pricing|Escritórios de vendas|Migração de clientes","decisoes":"Finalizar hierarquia comercial no ECC|Montar lista de escritórios de vendas|Migrar clientes para nova estrutura|Ajustar workflow pricing por níveis","problemas":"","acoes":"Gimenes/Ciorlia/Riqueti: Finalizar hierarquia comercial|Gimenes/Rhein/Ciorlia: Montar lista escritórios|Pereira/Pinheiro/França: Extrair base clientes|Pinheiro/Victoria/Pereira: Ajustar workflow pricing","jornadas_relacionadas":"hub-gestao|workflow-pricing|areas-vendas|cadastro-cliente"}');

-- Reuniao R7: Alinhamento Cadastro de Materiais
INSERT INTO projeto_dados (projeto_id, entidade_id, dados)
VALUES (5, 20, '{"id":"R7","data":"2025-12-23","titulo":"Alinhamento Cadastro de Materiais e Hierarquias","duracao":"30 min","tipo":"tecnico","resumo":"Discussão técnica sobre hierarquia de grupo de mercadoria no SAP. GPS (Product Groups) será base para segmentação, substituindo tabela de depara manual. Discutida precificação diferenciada por tipo de cliente (AMD, atacado, revenda, cooperativa).","participantes":"Thalita Rhein|Luis Riqueti|Carla Barbosa|Fabiana Silva|Fernanda Monteiro|Hudson Silva|Ronildo","topicos":"Hierarquia de grupo de mercadoria|GPS como base de segmentação|Precificação por segmento|Clusterização|Impacto em relatórios","decisoes":"Segmento será agrupamento de GP|Precificação diferenciada por canal para próximo ano|Hudson avaliará aderência do cadastro de produtos","problemas":"GP pode ser diferente entre Monlevade e outras unidades","acoes":"","jornadas_relacionadas":"cadastro-cliente|workflow-pricing"}');

-- Reuniao R8: Construção Planilha DE/PARA para Migração
INSERT INTO projeto_dados (projeto_id, entidade_id, dados)
VALUES (5, 20, '{"id":"R8","data":"2025-12-29","titulo":"Construção Planilha DE/PARA para Migração","duracao":"50 min","tipo":"operacional","resumo":"Planejamento para migração de dados de clientes. Definido hard reboot da lista de clientes, removendo todos agentes e reatribuindo. Criação de novo campo Segmentos de Produto com 46 valores. Deadline crítico: não modificar estrutura de escritórios até 30/01.","participantes":"Leandro Gimenez|Thalita Rhein|Marcelo Almeida|Leandro Cruz|Fabricio França","topicos":"Hard reboot de clientes|Segmentação de clientes|Alocação por regional|46 segmentos de produto|Listas suspensas dependentes|EVC para clientes sem regional","decisoes":"Hard reboot em 1-2 meses|Não criar escritórios até 30/01|Campo segmentos de produto no próximo sprint|EVC como escritório padrão para sem regional","problemas":"","acoes":"Gimenes: Hard reboot da lista|Almeida: Criar Service Requests novos escritórios|Gimenes: Finalizar segment report até 30/01|Victoria: Criar campo segmentos de produto","jornadas_relacionadas":"cadastro-cliente|areas-vendas|hub-gestao"}');

-- Reuniao R9: Bot Einstein - Autoatendimento WhatsApp e Logística
INSERT INTO projeto_dados (projeto_id, entidade_id, dados)
VALUES (5, 20, '{"id":"R9","data":"2026-01-07","titulo":"Bot Einstein - Autoatendimento WhatsApp e Logística","duracao":"52 min","tipo":"produto","resumo":"Apresentação do chatbot WhatsApp MVP para autoatendimento. Sistema oferece conversa guiada para consultas de conta, status de pedidos e documentos fiscais. Autenticação por validação de email cadastrado no Salesforce. Quando chatbot não resolve, cria caso para Smart Center.","participantes":"Fabricio França|Ricardo Accioly|Fabiana Silva|Ronildo|Jefferson Pinheiro|Patricia Miranda|Leandro Cruz|Marcelo Almeida|Gustavo Teixeira","topicos":"Chatbot WhatsApp MVP|Autenticação de clientes|Transbordo para Smart Center|Canal unificado|Integração Salesforce|Orçamento 2026","decisoes":"Mapear e priorizar fluxos do chatbot|Integrar Smart Center e SAC|Planejamento de licenças Salesforce","problemas":"","acoes":"França/Accioly/Silva: Mapeamento e priorização de fluxos|Miranda/Accioly: Integração Smart Center e SAC|Ronildo/Silva/Victoria: Testes e resolução de erros|Pereira/Pinheiro: Planejamento de licenças Salesforce","jornadas_relacionadas":"autoatendimento|hub-gestao|contatos"}');
